sudo: required

os:
  - linux
services:
  - docker

language: node_js
node_js:
  - "8.4.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add @angular/cli
install:
  - yarn install
script:
  - ng test --watch false
#  - ng e2e
deploy:
  - docker build -t gfoo/knarql-me .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push gfoo/knarql-me


notifications:
  email:
    on_failure: change
    on_success: change
